predictor/apps/playoff_teams/urls.py
from .views import PlayoffPickList, PlayoffPickUpdate, PlayoffPickListAll
from django.urls import re_path

app_name = 'playoff_teams'

urlpatterns = [
    re_path(r'^$', PlayoffPickList.as_view(), name='all'),               # individual picks
    re_path(r'^public/$', PlayoffPickListAll.as_view(), name='public'),  # everyone's picks
    re_path(r'^update/$', PlayoffPickUpdate.as_view(), name='update'),
]

# add this back above final div in playoffpick_list.html to re-enable playoff updates & uncomment above

predictor/urls.py
from django.urls import re_path, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'predictor'

urlpatterns = [
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    re_path(r"^test/$", views.TestPage.as_view(), name="test"),
    re_path(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    re_path(r"^HOF/$", views.HOFPage.as_view(), name="HOF"),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("predictor.apps.accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"^fixtures/", include("predictor.apps.fixtures.urls", namespace="fixtures")),
    re_path(r"^picks/", include("predictor.apps.picks.urls", namespace="picks")),
    re_path(r"^results/", include("predictor.apps.results.urls", namespace="results")),
    re_path(r"^playoff_teams/", include("predictor.apps.playoff_teams.urls", namespace="playoff_teams")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predictor/apps/playoff_teams/models.py
from django.db import models
from predictor.apps.fixtures.models import Team

from django.contrib.auth import get_user_model
User = get_user_model()


class PlayoffPick(models.Model):
    user = models.ForeignKey(User, related_name='playoff_pick', on_delete=models.CASCADE)
    afc_north = models.ForeignKey(Team, blank=True, null=True, related_name='afc_north', limit_choices_to={'division': 'AFC_NORTH'}, on_delete=models.CASCADE)
    nfc_north = models.ForeignKey(Team, blank=True, null=True, related_name='nfc_north', limit_choices_to={'division': 'NFC_NORTH'}, on_delete=models.CASCADE)
    afc_east = models.ForeignKey(Team, blank=True, null=True, related_name='afc_east', limit_choices_to={'division': 'AFC_EAST'}, on_delete=models.CASCADE)
    nfc_east = models.ForeignKey(Team, blank=True, null=True, related_name='nfc_east', limit_choices_to={'division': 'NFC_EAST'}, on_delete=models.CASCADE)
    afc_west = models.ForeignKey(Team, blank=True, null=True, related_name='afc_west', limit_choices_to={'division': 'AFC_WEST'}, on_delete=models.CASCADE)
    nfc_west = models.ForeignKey(Team, blank=True, null=True, related_name='nfc_west', limit_choices_to={'division': 'NFC_WEST'}, on_delete=models.CASCADE)
    afc_south = models.ForeignKey(Team, blank=True, null=True, related_name='afc_south', limit_choices_to={'division': 'AFC_SOUTH'}, on_delete=models.CASCADE)
    nfc_south = models.ForeignKey(Team, blank=True, null=True, related_name='nfc_south', limit_choices_to={'division': 'NFC_SOUTH'}, on_delete=models.CASCADE)
    afc_wild1 = models.ForeignKey(Team, blank=True, null=True, related_name='afc_wild1', limit_choices_to={'conference': 'AFC'}, on_delete=models.CASCADE)
    nfc_wild1 = models.ForeignKey(Team, blank=True, null=True, related_name='nfc_wild1', limit_choices_to={'conference': 'NFC'}, on_delete=models.CASCADE)
    afc_wild2 = models.ForeignKey(Team, blank=True, null=True, related_name='afc_wild2', limit_choices_to={'conference': 'AFC'}, on_delete=models.CASCADE)
    nfc_wild2 = models.ForeignKey(Team, blank=True, null=True, related_name='nfc_wild2', limit_choices_to={'conference': 'NFC'}, on_delete=models.CASCADE)
    afc_wild3 = models.ForeignKey(Team, blank=True, null=True, related_name='afc_wild3', limit_choices_to={'conference': 'AFC'}, on_delete=models.CASCADE)
    nfc_wild3 = models.ForeignKey(Team, blank=True, null=True, related_name='nfc_wild3', limit_choices_to={'conference': 'NFC'}, on_delete=models.CASCADE)
    sb_runner_up = models.ForeignKey(Team, blank=True, null=True, related_name='sb_runner_up', on_delete=models.CASCADE)
    sb_winner = models.ForeignKey(Team, blank=True, null=True, related_name='sb_winner', on_delete=models.CASCADE)

    def __str__(self):
        return ' '.join([
            self.user.username,
            "'s playoff picks",
        ])

predictor/apps/playoff_teams/views.py
from django.views import generic
from .models import PlayoffPick
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class PlayoffPickList(LoginRequiredMixin, generic.ListView):
    model = PlayoffPick

    def get_queryset(self):
        return PlayoffPick.objects.filter(user=self.request.user)


class PlayoffPickListAll(LoginRequiredMixin, generic.ListView):
    model = PlayoffPick
    template_name = 'playoff_teams/playoffpick_list.html'

    def get_queryset(self):
        return PlayoffPick.objects.all()


class PlayoffPickUpdate(LoginRequiredMixin, generic.UpdateView):
    model = PlayoffPick
    fields = (
        'afc_north',
        'nfc_north',
        'afc_east',
        'nfc_east',
        'afc_west',
        'nfc_west',
        'afc_south',
        'nfc_south',
        'afc_wild1',
        'nfc_wild1',
        'afc_wild2',
        'nfc_wild2',
        'afc_wild3',
        'nfc_wild3',
        'sb_runner_up',
        'sb_winner'
        )
    # template_name = 'playoffpick_update.html'
    success_url = reverse_lazy('playoff_teams:all')

    def get_object(self):
        return PlayoffPick.objects.get(user=self.request.user)

predictor/apps/playoff_teams/templates/playoff_teams/playoffpick_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<hr><hr><hr>
<div class="container">
  <h3>SELECT PLAYOFF TEAMS</h3>

  <form method="POST">
    {% csrf_token %}

    <table class="table">
      <th><img src="{% static 'images/AFC.png' %}" style="width:40px;height:40px;">AFC</th>
      <th></th>
      <th><img src="{% static 'images/NFC.png' %}" style="width:40px;height:40px;">NFC</th>
      <th></th>

      <tr>
      {% for field in form %}
          <td>{{field.label|upper}}</td><td>{{field}}</td>   
        {% if forloop.counter|divisibleby:2 %}</tr><tr>{% endif %}

      {% endfor %}
    </tr>
    </table>

    <input type="submit" class='btn btn-primary' value="Submit">

  </form>
</div>
{% endblock %}

predictor/apps/playoff_teams/templates/playoff_teams/playoffpick_list.html
{% extends 'picks/pick_base.html' %}
{% load static %}
{% block picks_content %}

  <div class="container">
    <a class="btn btn-success" style="width:200px;" href="{% url 'playoff_teams:update' %}">UPDATE</a>
    <!-- <a class="btn btn-success" style="width:200px;" href="{% url 'playoff_teams:public' %}">All Picks</a> -->
    {% for pick in object_list %}
      <h5>PLAYOFF TEAMS AS PICKED BY <strong>@{{pick.user.username}}</strong></h5>

    <table class="table table-striped">
      <thead>
        <th><img src="{% static 'images/AFC.png' %}" style="width:40px;height:40px;"> AFC</th>
        <th>TEAM</th>
        <th></th>
        <th></th>
        <th><img src="{% static 'images/NFC.png' %}" style="width:40px;height:40px;"> NFC</th>
        <th>TEAM</th>
      </thead>
      <tbody>

        <tr>
          <td>AFC NORTH</td>
          <td><img src="{% static pick.afc_north.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.afc_north.team_name}}</td>
          <td>  </td>
          <td>  </td>
          <td>NFC NORTH</td>
          <td><img src="{% static pick.nfc_north.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.nfc_north.team_name}}</td>
        </tr>

        <tr>
          <td>AFC EAST</td>
          <td><img src="{% static pick.afc_east.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.afc_east.team_name}}</td>
          <td></td>
          <td></td>
          <td>NFC EAST</td>
          <td><img src="{% static pick.nfc_east.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.nfc_east.team_name}}</td>
        </tr>

        <tr>
          <td>AFC SOUTH</td>
          <td><img src="{% static pick.afc_south.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.afc_south.team_name}}</td>
          <td></td>
          <td></td>
          <td>NFC SOUTH</td>
          <td><img src="{% static pick.nfc_south.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.nfc_south.team_name}}</td>
        </tr>

        <tr>
          <td>AFC WEST</td>
          <td><img src="{% static pick.afc_west.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.afc_west.team_name}}</td>
          <td></td>
          <td></td>
          <td>NFC WEST</td>
          <td><img src="{% static pick.nfc_west.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.nfc_west.team_name}}</td>
        </tr>

        <tr>
          <td>AFC WILDCARD 1</td>
          <td><img src="{% static pick.afc_wild1.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.afc_wild1.team_name}}</td>
          <td></td>
          <td></td>
          <td>NFC WILDCARD 1</td>
          <td><img src="{% static pick.nfc_wild1.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.nfc_wild1.team_name}}</td>
        </tr>

        <tr>
          <td>AFC WILDCARD 2</td>
          <td><img src="{% static pick.afc_wild2.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.afc_wild2.team_name}}</td>
          <td></td>
          <td></td>
          <td>NFC WILDCARD 2</td>
          <td><img src="{% static pick.nfc_wild2.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.nfc_wild2.team_name}}</td>
        </tr>

        <tr>
          <td>AFC WILDCARD 3</td>
          <td><img src="{% static pick.afc_wild3.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.afc_wild3.team_name}}</td>
          <td></td>
          <td></td>
          <td>NFC WILDCARD 3</td>
          <td><img src="{% static pick.nfc_wild3.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.nfc_wild3.team_name}}</td>
        </tr>


        <tr>
          <td>SB RUNNER UP</td>
          <td><img src="{% static pick.sb_runner_up.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.sb_runner_up.team_name}}</td>
          <td>  </td>
          <td>  </td>
          <td>SB WINNER</td>
          <td><img src="{% static pick.sb_winner.team_logo %}" alt="No team chosen" style="width:40px;height:40px;">    {{pick.sb_winner.team_name}}</td>
        </tr>

      </tbody>
    </table>

    <hr>

    {% endfor %}

  </div>
{% endblock %}