predictor/apps/picks/urls.py
from django.urls import re_path

from . import views

app_name = 'picks'

urlpatterns = [
    re_path(r"^$", views.ListSpecificWeekPicks.as_view(), name="all"),
    re_path(r'^update/$', views.update_picks, name='update'),
    re_path(r'^public/$', views.ListSubmittedWeekPicks.as_view(), name='public'),
    re_path(r'^check/$', views.ListAllWeekPicks.as_view(), name='check'),
    re_path(r'^simple/$', views.ListSimpleWeekPicks.as_view(), name='check'),
]

predictor/urls.py
from django.urls import re_path, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'predictor'

urlpatterns = [
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    re_path(r"^test/$", views.TestPage.as_view(), name="test"),
    re_path(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    re_path(r"^HOF/$", views.HOFPage.as_view(), name="HOF"),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("predictor.apps.accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"^fixtures/", include("predictor.apps.fixtures.urls", namespace="fixtures")),
    re_path(r"^picks/", include("predictor.apps.picks.urls", namespace="picks")),
    re_path(r"^results/", include("predictor.apps.results.urls", namespace="results")),
    re_path(r"^playoff_teams/", include("predictor.apps.playoff_teams.urls", namespace="playoff_teams")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predictor/apps/picks/models.py
from django.db import models
from predictor.apps.fixtures.models import Fixture
from django import template
from django.contrib.auth import get_user_model

register = template.Library()
User = get_user_model()


class Pick(models.Model):
    fixture = models.ForeignKey(Fixture, related_name='users_who_picked', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='picks', on_delete=models.CASCADE)
    home_pick = models.PositiveIntegerField(null=True, blank=True)
    away_pick = models.PositiveIntegerField(null=True, blank=True)
    lock = models.BooleanField(default=False)

    def _get_winner(self):
        if self.home_pick is not None and self.away_pick is not None:
            if self.home_pick > self.away_pick:
                return self.fixture.home_team
            if self.away_pick > self.home_pick:
                return self.fixture.away_team
            else:
                return "Tie"
        else:
            return "Not played"
    predicted_winner = property(_get_winner)

    def _get_margin(self):
        if self.home_pick is not None and self.away_pick is not None:
            return abs(self.home_pick - self.away_pick)
        else:
            return 5000
    predicted_margin = property(_get_margin)

    def _get_totalpts(self):
        if self.home_pick is not None and self.away_pick is not None:
            return self.home_pick + self.away_pick
        else:
            return 5000
    predicted_total_pts = property(_get_totalpts)

    def _winner_pts(self):
        if self.predicted_winner == self.fixture.winner:
            return 25
        else:
            return 0
    winner_pts = property(_winner_pts)

    def _margin_pts(self):
        return max(10 - abs(self.predicted_margin - self.fixture.margin), 0)
    margin_pts = property(_margin_pts)

    def _totalpts_pts(self):
        return max(10 - abs(self.predicted_total_pts - self.fixture.total_pts), 0)
    totalpts_pts = property(_totalpts_pts)

    def _get_total_score(self):
        return self.winner_pts + self.margin_pts + self.totalpts_pts
    points_scored = property(_get_total_score)

    def __str__(self):
        return ' '.join([
            self.user.username,
            " - ",
            "Week",
            str(self.fixture.week),
            " - ",
            self.fixture.away_team.team_name,
            " @ ",
            self.fixture.home_team.team_name,
        ])

predictor/apps/picks/forms.py
from django import forms
from django.forms.models import modelformset_factory
from .models import Pick


class PickForm(forms.ModelForm):
    class Meta:
        model = Pick
        exclude = ()


PickFormSetBase = modelformset_factory(Pick, extra=0, form=PickForm,
                                       fields=('fixture', 'away_pick', 'home_pick', 'lock'))

predictor/apps/picks/views.py
from django.shortcuts import redirect, render
from .models import Pick
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import PickFormSetBase
from scripts.get_week import get_week
from datetime import datetime, timezone, timedelta


# All weeks' picks for logged-in user
class ListSpecificWeekPicks(LoginRequiredMixin, generic.ListView):
    model = Pick

    def get_context_data(self, **kwargs):
        context = super(ListSpecificWeekPicks, self).get_context_data(**kwargs)
        q = self.request.GET.get("week", get_week())
        context['input'] = q
        return context

    def get_queryset(self):
        # If all selected, don't filter, just order
        if self.request.GET.get("week") == 'All':
            queryset = Pick.objects.filter(
                user=self.request.user,
                fixture__changeable=1,
                fixture__ko_datetime__gt=datetime.now(timezone.utc) - timedelta(hours=3)
            ).order_by('fixture__ko_datetime')

        # if a week is defined, filter on that
        elif self.request.GET.get("week"):
            selection = self.request.GET.get("week")
            queryset = Pick.objects.filter(
                user=self.request.user,
                fixture__week=selection,
                fixture__changeable=1,
                fixture__ko_datetime__gt=datetime.now(timezone.utc) - timedelta(hours=3)
            ).order_by('fixture__ko_datetime')

        # otherwise filter to current week
        else:
            queryset = Pick.objects \
                .filter(user=self.request.user,
                        fixture__changeable=1,
                        fixture__week=get_week()) \
                .order_by('fixture__ko_datetime')

        return queryset


# All Users' picks less than 1hr to KO, in play or completed
class ListSubmittedWeekPicks(LoginRequiredMixin, generic.ListView):
    model = Pick
    template_name = 'picks/pick_submitted.html'

    def get_context_data(self, **kwargs):
        context = super(ListSubmittedWeekPicks, self).get_context_data(**kwargs)
        q = self.request.GET.get("week", get_week())
        context['input'] = q
        return context

    def get_queryset(self):
        # If all selected, don't filter, just order
        if self.request.GET.get("week") == 'All':
            queryset = Pick.objects.filter(
                fixture__changeable=1,
                fixture__ko_datetime__lt=datetime.now(timezone.utc) - timedelta(hours=3),
            ).order_by('fixture__ko_datetime')

        # if a week is defined, filter on that
        elif self.request.GET.get("week"):
            selection = self.request.GET.get("week")
            queryset = Pick.objects.filter(
                fixture__week=selection,
                fixture__changeable=1,
                fixture__ko_datetime__lt=datetime.now(timezone.utc) - timedelta(hours=3)
            ).order_by('fixture__ko_datetime')

        # otherwise filter to current week
        else:
            queryset = Pick.objects \
                .filter(fixture__week=get_week(),
                        fixture__changeable=1,
                        fixture__ko_datetime__lt=datetime.now(timezone.utc) - timedelta(hours=3)) \
                .order_by('fixture__ko_datetime')
        return queryset


# All Users' picks
class ListAllWeekPicks(LoginRequiredMixin, generic.ListView):
    model = Pick
    template_name = 'picks/pick_check.html'

    def get_context_data(self, **kwargs):
        context = super(ListAllWeekPicks, self).get_context_data(**kwargs)
        q = self.request.GET.get("week", get_week())
        context['input'] = q
        return context

    def get_queryset(self):
        # If all selected, don't filter, just order
        if self.request.GET.get("week") == 'All':
            queryset = Pick.objects \
                .filter(fixture__changeable=1) \
                .order_by('fixture__ko_datetime')

        # if a week is defined, filter on that
        elif self.request.GET.get("week"):
            selection = self.request.GET.get("week")
            queryset = Pick.objects \
                .filter(fixture__week=selection,
                        fixture__changeable=1) \
                .order_by('fixture__ko_datetime')

        # otherwise filter to current week
        else:
            queryset = Pick.objects \
                .filter(fixture__week=get_week(),
                        fixture__changeable=1) \
                .order_by('fixture__ko_datetime')
        return queryset


# List all picks
class ListSimpleWeekPicks(LoginRequiredMixin, generic.ListView):
    model = Pick
    template_name = 'picks/pick_simple.html'

    def get_queryset(self):
        if self.request.GET.get("week"):
            selection = self.request.GET.get("week")
            queryset = Pick.objects \
                .filter(fixture__week=selection,
                        fixture__changeable=1) \
                .order_by('fixture__ko_datetime')
        else:
            queryset = Pick.objects \
                .filter(fixture__changeable=1)\
                .order_by('fixture__ko_datetime')
        return queryset


# Picks for logged-in user, for current week, with >1hr to KO
@login_required
def update_picks(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        this_week = get_week()
        formset = PickFormSetBase(
            request.POST,
            queryset=Pick.objects.filter(
                fixture__ko_datetime__gt=datetime.now(timezone.utc) - timedelta(hours=5),
                user=request.user,
                fixture__week=this_week,
                fixture__changeable=1,
            ).order_by('fixture__ko_datetime')
        )

        print(formset.errors)
        if formset.is_valid():
            for form in formset.forms:
                if action == 'save':
                    form.save()

        redirect('picks:all')

    else:
        formset = PickFormSetBase(
            queryset=Pick.objects.filter(
                fixture__changeable=1,
                fixture__ko_datetime__gt=datetime.now(timezone.utc) - timedelta(hours=5),
                user=request.user,
                fixture__week=get_week()).order_by('fixture__ko_datetime')
        )

    return render(request, 'picks/pick_form.html', {'formset': formset})

predictor/apps/picks/templates/picks/pick_base.html
{% extends "base.html" %}
{% block content %}

<br>
<br>
<br>

<div class="container">
  <div class="row">

    <a class="btn btn-primary" style="width:200px;" href="{% url 'picks:all' %}">MY PICKS</a>
    <a class="btn btn-info" style="width:200px;" href="{% url 'picks:update' %}">UPDATE PICKS</a>
    <a class="btn btn-success" style="width:200px;" align="center" href="{% url 'picks:public' %}">EVERYONE'S PICKS</a>
{#    <a class="btn btn-danger" style="width:200px;" align="center" href="{% url 'playoff_teams:all' %}">PLAYOFF PICKS</a>#}
    <a class="btn btn-danger" style="width:200px;" align="center" href="{% url 'playoff_teams:public' %}">ALL PLAYOFF PICKS</a>
<hr>
    {% block prepicks %}{% endblock %}
    {% block picks_content %}{% endblock %}
    {% block post_picks %}{% endblock %}
  </div>
</div>

{% endblock %}

predictor/apps/picks/templates/picks/pick_check.html
{% extends "picks/pick_base.html" %}
{% load static %}
{% block prepicks %}


<P>ALL PICKS</P>
<form class="form-inline" method="GET">
    <label for="week">SELECT WEEK : </label>

    <select name="week">
        {% for ii in "xxxxxxxxxxxxxxxxxxxxxx" %}
            {% if forloop.counter == input|add:"0" %}
                <option selected="selected">{{ forloop.counter }}</option>
            {% else %}
                <option>{{ forloop.counter }}</option>
            {% endif %}
        {% endfor %}

        {% if input == "All" %}
            <option selected="selected">All</option>
        {% else %}
            <option>All</option>
        {% endif %}
    </select>
    <input type="submit" value="Submit"/>
</form>

<table class="table">
  <colgroup>
   <col span="1" style="width: 5%;">
   <col span="1" style="width: 22%;">
   <col span="1" style="width: 5%;">
   <col span="1" style="width: 17%;">
   <col span="1" style="width: 17%;">
   <col span="1" style="width: 17%;">
   <col span="1" style="width: 17%;">

<thead>
  <th>Week</th>
  <th>Away @ Home </th>
  <th><hr width="1" size="500"></th>
  <th>conorspicer</th>
  <th>torinmehmet</th>
  <th>magnusmartinsen</th>
  <th>lewismead</th>
  <th>lukeconboy</th>
{# TODO - add new username(s) #}
</thead>

<tbody>

  {% for pick in object_list %}
    {# TODO - increment counter #}
    {% if forloop.counter0|divisibleby:5 %}
      <tr>
        <td>{{pick.fixture.week}}</td>
        <td align="center"><img src="{% static pick.fixture.away_team.team_logo %}" style="width:40px;height:40px;">
          @
          <img src="{% static pick.fixture.home_team.team_logo %}" style="width:40px;height:40px;"></td>
        <td>|</td>
        <td><img src="{% static pick.predicted_winner.team_logo %}" style="width:40px;height:40px;">
          <strong>{{pick.predicted_margin}}</strong>,
          <strong>{{pick.predicted_total_pts}}</strong>
          {% if pick.lock %} <img src="{% static 'images/lock.png' %}" style="width:40px;height:40px;"> {% else %}{% endif %}
        </td>
    {# TODO - increment counter #}
    {% elif forloop.counter|divisibleby:5 %}
      <td><img src="{% static pick.predicted_winner.team_logo %}" style="width:40px;height:40px;">
        <strong>{{pick.predicted_margin}}</strong>,
        <strong>{{pick.predicted_total_pts}}</strong>
        {% if pick.lock %} <img src="{% static 'images/lock.png' %}" style="width:40px;height:40px;"> {% else %}{% endif %}
      </td>
    </tr>
    {% else %}
      <td><img src="{% static pick.predicted_winner.team_logo %}" style="width:40px;height:40px;">
        <strong>{{pick.predicted_margin}}</strong>,
        <strong>{{pick.predicted_total_pts}}</strong>
        {% if pick.lock %} <img src="{% static 'images/lock.png' %}" style="width:40px;height:40px;"> {% else %}{% endif %}
      </td>
    {% endif %}

  {% endfor %}
</tbody>
</table>

{% endblock %}

predictor/apps/picks/templates/picks/pick_form.html
{% extends "picks/pick_base.html" %}
{% load static %}

{% block picks_content %}
<h5>Make picks or update them here</h5>
<p>The only picks which will be shown are games for the current week which have not been played yet. Picks are locked approx. 1 hour before KO</p>


  <form method="POST" action="">
    {% csrf_token %}

    <table class="table table-striped">
      <thead>
        <th>Fixture</th>
        <th>Away Score</th>
        <th>@</th>
        <th>Home Score</th>
        <th>Lock</th>
      </thead>

    {% for form in formset %}
      <tr>
        <td><strong>{{form.instance.fixture}} {{ form.fixture.as_hidden }}</strong></td>

        <td>
          <img src="{% static form.instance.fixture.away_team.team_logo %}" style="width:40px;height:40px;">
          {{form.away_pick}}
        </td>
        <td> <strong>@</strong> </td>
        <td>
          <img src="{% static form.instance.fixture.home_team.team_logo %}" style="width:40px;height:40px;">
          {{form.home_pick}}
        </td>
        <td> {{form.lock}} </td>
        {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
      </tr>
    {% endfor %}

      </tr>
    </table>

    {{ formset.management_form }}

      <button type="submit" name="action" value="save">Save</button>
  </form><br>



{% endblock %}

predictor/apps/picks/templates/picks/pick_list.html
{% extends "picks/pick_base.html" %}
{% load static %}
{% block prepicks %}

 <h5>PICKS FOR: <strong>@{{user.username}}</strong> {% if input %}FOR WEEK: {{input}}{% else %}{% endif %}</h5>

<hr>
<form class="form-inline" method="GET">
    <label for="week">SELECT WEEK : </label>

    <select name="week">
        {% for ii in "xxxxxxxxxxxxxxxxxxxxxx" %}
            {% if forloop.counter == input|add:"0" %}
                <option selected="selected">{{ forloop.counter }}</option>
            {% else %}
                <option>{{ forloop.counter }}</option>
            {% endif %}
        {% endfor %}

        {% if input == "All" %}
            <option selected="selected">All</option>
        {% else %}
            <option>All</option>
        {% endif %}
    </select>
    <input type="submit" value="Submit"/>
</form>

<div class="col-lg-12">
<table class="table table-striped">
	<thead>
    <th>Week </th>
		<th>Away </th>
    <th>Prediction</th>
		<th>Home </th>
		<th>Kick Off</th>
    <th>Winner</th>
    <th>Margin</th>
    <th>TP</th>
    <th>Lock</th>
	</thead>

  {% for pick in object_list %}
  	<tr>
      <td>{{ pick.fixture.week }}</td>
  		<td><img src="{% static pick.fixture.away_team.team_logo %}" style="width:40px;height:40px;">
  			  {{ pick.fixture.away_team }}</td>
  		<td>{{ pick.away_pick }}      -     {{ pick.home_pick }}</td>
  		<td><img src="{% static pick.fixture.home_team.team_logo %}" style="width:40px;height:40px;">
  			  {{ pick.fixture.home_team }}</td>

  		<td>{{ pick.fixture.ko_datetime }}</td>
      <td align="right">{{ pick.winner_pts }}</td>
      <td align="right">{{ pick.margin_pts }}</td>
      <td align="right">{{ pick.totalpts_pts }}</td>
      <td>{% if pick.lock %} <img src="{% static 'images/lock.png' %}" style="width:40px;height:40px;"> {% else %}{% endif %}</td>
  	</tr>
  {% endfor %}

</table>
</div>

{% endblock %}

predictor/apps/picks/templates/picks/pick_submitted.html
{% extends "picks/pick_base.html" %}
{% load static %}
{% block prepicks %}


<P>PICKS WILL ONLY APPEAR HERE ONCE THEY CAN NO LONGER BE CHANGED</P>
<form class="form-inline" method="GET">
    <label for="week">SELECT WEEK : </label>

    <select name="week">
        {% for ii in "xxxxxxxxxxxxxxxxxxxxxx" %}
            {% if forloop.counter == input|add:"0" %}
                <option selected="selected">{{ forloop.counter }}</option>
            {% else %}
                <option>{{ forloop.counter }}</option>
            {% endif %}
        {% endfor %}

        {% if input == "All" %}
            <option selected="selected">All</option>
        {% else %}
            <option>All</option>
        {% endif %}
    </select>
    <input type="submit" value="Submit"/>
</form>

<table class="table">
    <colgroup>
        <col span="1" style="width: 5%;">
        <col span="1" style="width: 22%;">
        <col span="1" style="width: 5%;">
        <col span="1" style="width: 17%;">
        <col span="1" style="width: 17%;">
        <col span="1" style="width: 17%;">
        <col span="1" style="width: 17%;">

    <thead>
    <th>Week</th>
    <th>Away @ Home</th>
    <th>
        <hr width="1" size="500">
    </th>
    <th>conorspicer</th>
    <th>torinmehmet</th>
    <th>magnusmartinsen</th>
    <th>lewismead</th>
    <th>lukeconboy</th>
    {# TODO - add new username(s) #}
    </thead>

    <tbody>

    {% for pick in object_list %}

    {# TODO - increment counter? #}
    {% if forloop.counter0|divisibleby:5 %}
    <tr>
        <td>{{pick.fixture.week}}</td>
        <td align="center"><img src="{% static pick.fixture.away_team.team_logo %}" style="width:40px;height:40px;">
            @
            <img src="{% static pick.fixture.home_team.team_logo %}" style="width:40px;height:40px;"></td>
        <td>|</td>
        <td><img src="{% static pick.predicted_winner.team_logo %}" style="width:40px;height:40px;">
            <strong>{{pick.predicted_margin}}</strong>,
            <strong>{{pick.predicted_total_pts}}</strong>
            {% if pick.lock %} <img src="{% static 'images/lock.png' %}" style="width:40px;height:40px;"> {% else %}{% endif %}
        </td>
    {# TODO - increment counter #}
    {% elif forloop.counter|divisibleby:5 %}
        <td><img src="{% static pick.predicted_winner.team_logo %}" style="width:40px;height:40px;">
            <strong>{{pick.predicted_margin}}</strong>,
            <strong>{{pick.predicted_total_pts}}</strong>
            {% if pick.lock %} <img src="{% static 'images/lock.png' %}" style="width:40px;height:40px;"> {% else %}{% endif %}
        </td>
    </tr>
    {% else %}
    <td><img src="{% static pick.predicted_winner.team_logo %}" style="width:40px;height:40px;">
        <strong>{{pick.predicted_margin}}</strong>,
        <strong>{{pick.predicted_total_pts}}</strong>
        {% if pick.lock %} <img src="{% static 'images/lock.png' %}" style="width:40px;height:40px;"> {% else %}{% endif %}
    </td>
    {% endif %}

    {% endfor %}
    </tbody>
</table>

{% endblock %}