predictor/apps/accounts/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    re_path(r"login/$",
            auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    re_path(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
]

predictor/apps/picks/urls.py
from django.urls import re_path

from . import views

app_name = 'picks'

urlpatterns = [
    re_path(r"^$", views.ListSpecificWeekPicks.as_view(), name="all"),
    re_path(r'^update/$', views.update_picks, name='update'),
    re_path(r'^public/$', views.ListSubmittedWeekPicks.as_view(), name='public'),
    re_path(r'^check/$', views.ListAllWeekPicks.as_view(), name='check'),
    re_path(r'^simple/$', views.ListSimpleWeekPicks.as_view(), name='check'),
]

predictor/urls.py
from django.urls import re_path, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'predictor'

urlpatterns = [
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    re_path(r"^test/$", views.TestPage.as_view(), name="test"),
    re_path(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    re_path(r"^HOF/$", views.HOFPage.as_view(), name="HOF"),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("predictor.apps.accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"^fixtures/", include("predictor.apps.fixtures.urls", namespace="fixtures")),
    re_path(r"^picks/", include("predictor.apps.picks.urls", namespace="picks")),
    re_path(r"^results/", include("predictor.apps.results.urls", namespace="results")),
    re_path(r"^playoff_teams/", include("predictor.apps.playoff_teams.urls", namespace="playoff_teams")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/HOF.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br><br>
<div class="container">
  <table class="table table-striped">

    <thead>
      <th>Year</th>
      <th>Winner</th>
      <th>Points</th>
      <th>Jersey</th>
    </thead>

    <tbody>
      <tr>
        <td>2014</td>
        <td>Magnus Martinsen</td>
        <td>2292*</td>
        <td><img src="{% static 'logos/minnesota-vikings-logo-vector.png' %}" alt="" style="width:50px;height:50px;"> 5 - Teddy Bridgewater </td>
      </tr>

      <tr>
        <td>2015</td>
        <td>Magnus Martinsen</td>
        <td>4679</td>
        <td><img src="{% static 'logos/cleveland-browns-vector-logo.png' %}" alt="" style="width:50px;height:50px;"> 2 - Johnny Manziel </td>
      </tr>

      <tr>
        <td>2016</td>
        <td>Conor Spicer</td>
        <td>5101</td>
        <td><img src="{% static 'logos/jacksonville-jaguars-vector-logo.png' %}" alt="" style="width:50px;height:50px;">  88 - Allen Hurns </td>
      </tr>

      <tr>
        <td>2017</td>
        <td>Conor Spicer</td>
        <td>6625</td>
        <td><img src="{% static 'logos/philadelphia-eagles-logo-vector.png' %}" alt="" style="width:50px;height:50px;">  9 - Nick Foles </td>
      </tr>

      <tr>
        <td>2018</td>
        <td>Lewis Mead</td>
        <td>6779</td>
        <td><img src="{% static 'logos/tennessee-titans-vector-logo.png' %}" alt="" style="width:50px;height:50px;">  8 - Mariota </td>
      </tr>

      <tr>
        <td>2019</td>
        <td>Torin Mehmet</td>
        <td>6396</td>
        <td><img src="{% static 'logos/green-bay-packers-logo-vector.png' %}" alt="" style="width:50px;height:50px;">  17 - Adams </td>
      </tr>

      <tr>
        <td>2020</td>
        <td>Conor Spicer</td>
        <td>6947</td>
        <td><img src="{% static 'logos/tampa-bay-buccaneers-logo-vector.png' %}" alt="" style="width:50px;height:50px;">  12 - Tom Brady </td>
      </tr>

      <tr>
        <td>2021</td>
        <td>Conor Spicer</td>
        <td>7097</td>
        <td><img src="{% static 'logos/pittsburgh-steelers-logo-vector-01.png' %}" alt="" style="width:50px;height:50px;">  7 - Ben Roethlisberger </td>
      </tr>
      
      <tr>
        <td>2022</td>
        <td>Lewis Mead</td>
        <td>7070</td>
        <td><img src="{% static 'logos/tennessee-titans-vector-logo.png' %}" alt="" style="width:50px;height:50px;">  22 - Derrick Henry* </td>
      </tr>
    </tbody>

  </table>
</div>

<!--<section class="mbr-section" id="msg-box4-1" style="background-color: rgb(242, 242, 242); padding-top: 120px; padding-bottom: 120px;">-->

    <!--<div class="container">-->
        <!--<div class="row">-->
            <!--<div class="mbr-table-md-up">-->

              <!--<div class="mbr-table-cell mbr-right-padding-md-up mbr-valign-top col-md-7 image-size" style="width: 50%;">-->
                  <!--<div class="mbr-figure"><iframe class="mbr-embedded-video" src="https://www.youtube.com/embed/K3SlVsdUuBY" width="1280" height="720" frameborder="0" allowfullscreen></iframe></div>-->
              <!--</div>-->


              <!--<div class="mbr-table-cell col-md-5 text-xs-center text-md-left content-size">-->
                  <!--<h3 class="mbr-section-title display-2">ITS DRAFT DAY!!</h3>-->


                  <!--<div><a class="btn btn-primary" href="https://www.google.co.uk/search?hl=en&q=draft+day&meta=">MORE</a></div>-->
              <!--</div>-->

            <!--</div>-->
        <!--</div>-->
    <!--</div>-->

<!--</section>-->

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'images/football.png' %}" type="image/png">
  <meta name="description" content="">
  <title>NFL Predictor</title>

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;subset=latin">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
  <link rel="stylesheet" href="{% static 'bootstrap-material-design-font/css/material.css' %}">
  <link rel="stylesheet" href="{% static 'web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'mobirise/css/mbr-additional.css' %}" type="text/css">

</head>


<body>
  {# Navbar section #}
  <section id="menu-0">

      <nav class="navbar navbar-dropdown bg-color navbar-fixed-top">
          <div class="container">

              <div class="mbr-table">
                  <div class="mbr-table-cell">

                      <div class="navbar-brand">
                        <a class="navbar-caption" href="{% url 'home' %}">
                          <span class="navbar-logo"><span class="mbri-home mbr-iconfont mbr-iconfont-menu"></span></span>
                        </a>
                      </div>

                  </div>
                  <div class="mbr-table-cell">

                      <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                          <div class="hamburger-icon"></div>
                      </button>

                      <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm" id="exCollapsingNavbar">
                        <li class="nav-item"><a class="nav-link link" href="{% url 'admin:index' %}">ADMIN</a></li>
                        <li class="nav-item"><a class="nav-link link" href="{% url 'fixtures:all' %}">FIXTURES</a></li>
                        <li class="nav-item"><a class="nav-link link" href="{% url 'picks:all' %}">PICKS</a></li>
                        <li class="nav-item"><a class="nav-link link" href="{% url 'results:all' %}">SCORES</a></li>
                        <li class="nav-item"><a class="nav-link link" href="{% url 'HOF' %}">HOF</a></li>

                        {% if user.is_authenticated %}
                          <li class="nav-item nav-btn"><a class="nav-link btn btn-white btn-white-outline" href="{% url 'accounts:logout' %}">LOGOUT</a></li>
                        {% else %}
                              <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link btn btn-white btn-white-outline">LOGIN</a></li>
                        {% endif %}
                      </ul>
                      <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                          <div class="close-icon"></div>
                      </button>

                  </div>
              </div>

          </div>
      </nav>

  </section>

<br><br>

  {% block content %}

  {% endblock %}



<footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="footer1-2" style="background-color: rgb(50, 50, 50); padding-top: 1.75rem; padding-bottom: 1.75rem;">

    <div class="container">
        <p class="text-xs-center">Copyright (c) 2023 Conor Spicer.</p>
    </div>
</footer>

  {% block footer %}

  {% endblock %}


  <script src="{% static 'web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'tether/tether.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'smooth-scroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'dropdown/js/script.min.js' %}"></script>
  <script src="{% static 'touch-swipe/jquery.touch-swipe.min.js' %}"></script>
  <script src="{% static 'viewport-checker/jquery.viewportchecker.js' %}"></script>
  <script src="{% static 'jarallax/jarallax.js' %}"></script>
  <script src="{% static 'bootstrap-carousel-swipe/bootstrap-carousel-swipe.js' %}"></script>
  <script src="{% static 'social-likes/social-likes.js' %}"></script>
  <script src="{% static 'theme/js/script.js' %}"></script>


  <input name="animation" type="hidden">
  </body>
</html>

templates/base0.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'images/football.png' %}" type="image/png">
  <meta name="description" content="">
  <title>NFL Predictor</title>

{#  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;subset=latin">#}
{#  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">#}
{#  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">#}
  <link rel="stylesheet" href="{% static 'bootstrap-material-design-font/css/material.css' %}">
  <link rel="stylesheet" href="{% static 'web/assets/mobirise-icons/mobirise-icons.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'tether/tether.min.css' %}"> -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'dropdown/css/style.css' %}">
  <!-- {# <link rel="stylesheet" href="{% static 'animate.css/animate.min.css' %}"> #} -->
  <!-- <link rel="stylesheet" href="{% static 'socicon/css/styles.css' %}"> -->
  <link rel="stylesheet" href="{% static 'theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'mobirise/css/mbr-additional.css' %}" type="text/css">

</head>


<body>
  {# Navbar section #}
  <section id="menu-0">

      <nav class="navbar navbar-dropdown bg-color transparent navbar-fixed-top">
          <div class="container">

              <div class="mbr-table">
                  <div class="mbr-table-cell">

                      <div class="navbar-brand">
                        <a class="navbar-caption" href="{% url 'home' %}">
                          <span class="navbar-logo"><span class="mbri-home mbr-iconfont mbr-iconfont-menu"></span></span>
                        </a>
                      </div>

                  </div>
                  <div class="mbr-table-cell">

                      <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                          <div class="hamburger-icon"></div>
                      </button>

                      <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm" id="exCollapsingNavbar">
                        <li class="nav-item"><a class="nav-link link" href="{% url 'admin:index' %}">ADMIN</a></li>
                        <li class="nav-item"><a class="nav-link link" href="{% url 'fixtures:all' %}">FIXTURES</a></li>
                        <li class="nav-item"><a class="nav-link link" href="{% url 'picks:all' %}">PICKS</a></li>
                        <li class="nav-item"><a class="nav-link link" href="{% url 'results:all' %}">SCORES</a></li>
                        <li class="nav-item"><a class="nav-link link" href="{% url 'HOF' %}">HOF</a></li>


                        {% if user.is_authenticated %}
                          <li class="nav-item nav-btn"><a class="nav-link btn btn-white btn-white-outline" href="{% url 'accounts:logout' %}">LOGOUT</a></li>
                        {% else %}
                              <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link btn btn-white btn-white-outline">LOGIN</a></li>
                        {% endif %}
                      </ul>
                      <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                          <div class="close-icon"></div>
                      </button>

                  </div>
              </div>

          </div>
      </nav>

  </section>

  {% block content %}

  {% endblock %}



<footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="footer1-2" style="background-color: rgb(50, 50, 50); padding-top: 1.75rem; padding-bottom: 1.75rem;">

    <div class="container">
        <p class="text-xs-center">Copyright (c) 2023 Conor Spicer.</p>
    </div>
</footer>


  <script src="{% static 'web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'tether/tether.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'smooth-scroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'dropdown/js/script.min.js' %}"></script>
  <script src="{% static 'touch-swipe/jquery.touch-swipe.min.js' %}"></script>
  <script src="{% static 'viewport-checker/jquery.viewportchecker.js' %}"></script>
  <script src="{% static 'jarallax/jarallax.js' %}"></script>
  <script src="{% static 'bootstrap-carousel-swipe/bootstrap-carousel-swipe.js' %}"></script>
  <script src="{% static 'social-likes/social-likes.js' %}"></script>
  <script src="{% static 'theme/js/script.js' %}"></script>


  <input name="animation" type="hidden">
  </body>
</html>

templates/index.html
{% extends "base0.html" %}

{% load static %}
{% block content %}

{# intro slide #}
{# <section class="engine"><a rel="external" href="https://mobirise.com">mobirise.com</a></section> #}
<section class="mbr-section mbr-section-hero mbr-section-full mbr-parallax-background mbr-section-with-arrow" id="header1-1" style="background-image: url({% static 'images/mbr-2000x1333.jpg'%}) ;">

    <div class="mbr-overlay" style="opacity: 0.5; background-color: rgb(0, 0, 0);"></div>

    <div class="mbr-table-cell">

        <div class="container">
            <div class="row">
                <div class="mbr-section col-md-10 col-md-offset-1 text-xs-center">

                    <h1 class="mbr-section-title display-1">NFL PREDICTOR</h1>
                    {% if user.is_authenticated %}
                      <div class="mbr-section-btn"><a class="btn btn-lg btn-primary" href="{% url 'picks:all' %}">PICKS</a> </div>
                    {% else %}
                      <div class="mbr-section-btn">
                        <a class="btn btn-lg btn-primary" href="{% url 'accounts:login' %}">LOGIN</a>
                       </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

    <div class="mbr-arrow mbr-arrow-floating" aria-hidden="true"><a href="#msg-box4-1"><i class="mbr-arrow-icon"></i></a></div>

</section>


<!--<section class="mbr-section" id="msg-box4-1" style="background-color: rgb(242, 242, 242); padding-top: 120px; padding-bottom: 120px;">-->

<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="mbr-table-md-up">-->
<!--              <div class="container">-->
<!--                <h2>CURRENT SCORES</h2>-->
<!--                <hr>-->
<!--                <ul style="list-style: none;">-->
<!--                  {% for r in totals %}-->
<!--                    <li ><h4><strong>{{r.total_points_scored}}</strong> - @{{r.user.username}}</h4></li>-->
<!--                  {% endfor %}-->
<!--                </ul><hr>-->
<!--              </div>-->

<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

<!--</section>-->



{% endblock %}

templates/test.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{# intro slide #}
<section class="engine"></section><section class="mbr-section mbr-section-hero mbr-section-full mbr-parallax-background mbr-section-with-arrow" id="header1-1" style="background-image: url({% static 'images/mbr-2000x1333.jpg'%});">

    <div class="mbr-overlay" style="opacity: 0.5; background-color: rgb(0, 0, 0);"></div>

    <div class="mbr-table-cell">

        <div class="container">
            <div class="row">
                <div class="mbr-section col-md-10 col-md-offset-1 text-xs-center">

                    <h1 class="mbr-section-title display-1">YOU ARE NOW LOGGED IN</h1>

                </div>
            </div>
        </div>
    </div>

</section>



{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{# intro slide #}
<section class="engine"></section><section class="mbr-section mbr-section-hero mbr-section-full mbr-parallax-background mbr-section-with-arrow" id="header1-1" style="background-image: url({% static 'images/mbr-2000x1333.jpg'%});">

    <div class="mbr-overlay" style="opacity: 0.5; background-color: rgb(0, 0, 0);"></div>

    <div class="mbr-table-cell">

        <div class="container">
            <div class="row">
                <div class="mbr-section col-md-10 col-md-offset-1 text-xs-center">

                    <h1 class="mbr-section-title display-1">THANKS FOR VISITING</h1>

                </div>
            </div>
        </div>
    </div>

    <div class="mbr-arrow mbr-arrow-floating" aria-hidden="true"><a href="#msg-box4-1"><i class="mbr-arrow-icon"></i></a></div>

</section>



{% endblock %}